Remove caption data from instagram queries
Resolves exceptions that look like:

error: cannot extract element from a scalar
    at Connection.parseE (/Users/seth/src/stamen/preview.parks.stamen.com/node_modules/pg/lib/connection.js:561:11)
    at Connection.parseMessage (/Users/seth/src/stamen/preview.parks.stamen.com/node_modules/pg/lib/connection.js:390:17)
    at null.<anonymous> (/Users/seth/src/stamen/preview.parks.stamen.com/node_modules/pg/lib/connection.js:98:18)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

These are caused by null values for metadata -> 'caption' in instagram_photos.